Repository EfthymiaKakoulidou/starathon, pull requests merged in 2024-05, with the labels that each got.

#53 feat: Stop timer and clear timer display when there are no more quest…
  static/js/index.js
Labels: could have

#69 Clarity for error 404 page
  404.html
  static/css/style.css
Labels: NTHNN

#75 feat: Add results at the end of a round. And add Star Wars Sounds to game.
  static/js/index.js
Labels: must have
